    const PROGRAM = [
      {day:1, title:'Pull Strength + Boxing Conditioning', type:'lift', warmup:'5–7 minutes: light jump rope or brisk walk, then shoulder mobility.', focus:'Posterior chain and upper-back strength with fighter-style conditioning. Keep loads light to moderate and stop well before breakdown.', exercises:[
        {n:'Deadlift', sets:3, reps:'5', incLb:5, incKg:2.5, tip:'Brace first, keep the bar close, and move with smooth tempo. Light to moderate only.'},
        {n:'Bent-over Row', sets:3, reps:'8', incLb:5, incKg:2.5, tip:'Hinge softly, keep the torso stable, and row to the lower ribs without jerking.'},
        {n:'Lat Pulldown', sets:3, reps:'10', incLb:5, incKg:2.5, tip:'Pull elbows down, chest tall, and avoid leaning way back.'},
        {n:'Dumbbell Row', sets:2, reps:'10', incLb:5, incKg:2.5, tip:'Support the spare hand, keep the spine neutral, and pull with the back not the neck.'},
        {n:'Face Pulls', sets:3, reps:'12', incLb:2.5, incKg:1, tip:'Lead with elbows, finish near eyebrow height, and pause briefly at the face.'},
        {n:'Hammer Curls', sets:2, reps:'12', incLb:2.5, incKg:1, tip:'Keep elbows pinned and wrists neutral. Control the lowering phase.'}
      ], finisher:'Conditioning: 10–15 minutes of heavy bag, speed bag, or shadowboxing. Keep rounds crisp, not exhausting.'},
      {day:2, title:'Push Strength + Power Work', type:'lift', warmup:'5 minutes of easy movement plus a couple of shoulder and pec mobility drills.', focus:'Pressing strength with controlled power. Strong reps, stable shoulders, and no grinding.', exercises:[
        {n:'Bench Press', sets:3, reps:'5', incLb:5, incKg:2.5, tip:'Feet planted, shoulder blades tucked, and bar path smooth. Leave a rep or two in reserve.'},
        {n:'Dumbbell Shoulder Press', sets:3, reps:'8', incLb:5, incKg:2.5, tip:'Use a pain-free range, ribs down, and avoid arching hard through the low back.'},
        {n:'Push-ups', sets:3, reps:'10', incLb:0, incKg:0, bodyweight:true, tip:'Use a bench elevation if needed. Keep the body in one line and move under control.'},
        {n:'Cable Lateral Raise', sets:2, reps:'12', incLb:2.5, incKg:1, tip:'Raise only to shoulder height and keep the neck relaxed.'},
        {n:'Tricep Rope Extension', sets:3, reps:'12', incLb:2.5, incKg:1, tip:'Elbows stay by the ribs. Finish gently without snapping the elbows.'}
      ], finisher:'Optional finisher: 5 minutes of battle ropes or medicine-ball throws. Keep it sharp and athletic, not maximal.'},
      {day:3, title:'Active Recovery', type:'recovery', warmup:'No aggressive warm-up needed. Ease in and keep it restorative.', focus:'Restore range of motion, get blood moving, and feel better leaving than when you started.', options:[
        {n:'Light cardio', d:'20–30 minutes of brisk walking, easy cycling, or relaxed treadmill work.'},
        {n:'Stretching / mobility', d:'10–20 minutes of hips, thoracic spine, shoulders, calves, and ankles.'},
        {n:'Creed ab circuit', d:'1–2 rounds max. Keep it smooth: plank, crunch, bicycle, leg raise, and sit-up variations.'}
      ], recoveryTip:'This is a recovery day, not a secret conditioning day. Stay conversational and finish refreshed.'},
      {day:4, title:'Legs (Joint-Friendly)', type:'lift', warmup:'5–7 minutes of easy movement, then hips, ankles, and glute activation.', focus:'Leg training that protects knees and low back while rebuilding strength and muscle safely.', exercises:[
        {n:'Trap Bar Deadlift', sets:3, reps:'5', incLb:5, incKg:2.5, tip:'Stand tall through the finish, push the floor away, and stop if the low back takes over.'},
        {n:'Leg Press', sets:3, reps:'10', incLb:10, incKg:5, tip:'Use a foot position that feels good on the knees and avoid bottoming out too deep.'},
        {n:'Dumbbell Lunges', sets:2, reps:'10 each', incLb:5, incKg:2.5, tip:'Shorter steps are fine. Use support if balance needs work.'},
        {n:'Hip Thrust', sets:2, reps:'10', incLb:5, incKg:2.5, tip:'Ribs down, squeeze glutes at the top, and do not hyperextend the low back.'},
        {n:'Leg Curl', sets:2, reps:'12', incLb:5, incKg:2.5, tip:'Move slowly and keep hips anchored to protect hamstrings and low back.'},
        {n:'Standing Calf Raise', sets:2, reps:'15', incLb:5, incKg:2.5, tip:'Pause briefly at the top and lower under full control.'}
      ], finisher:'No extra punishment needed. Walk a few minutes, breathe, and cool down.'},
      {day:5, title:'Full Body Muscle Builder', type:'lift', warmup:'5–7 minutes of easy movement, then a couple of rehearsal sets for the first two lifts.', focus:'A more muscle-building full-body session with moderate reps, joint-friendly support, and enough stimulus to grow without wrecking recovery.', exercises:[
        {n:'Leg Press', sets:3, reps:'12', incLb:10, incKg:5, tip:'Drive through the full foot, keep knees tracking comfortably, and stop shy of joint irritation.'},
        {n:'Incline Dumbbell Bench Press', sets:3, reps:'10', incLb:5, incKg:2.5, tip:'Use a moderate incline and a range that lets the shoulders feel stable.'},
        {n:'Chest-Supported Row', sets:3, reps:'10', incLb:5, incKg:2.5, tip:'Let the bench protect the low back and row under control with a pause at the top.'},
        {n:'Romanian Deadlift', sets:2, reps:'10', incLb:5, incKg:2.5, tip:'Soft knees, long spine, and stop when the hamstrings are loaded without back strain.'},
        {n:'Seated Dumbbell Shoulder Press', sets:2, reps:'12', incLb:5, incKg:2.5, tip:'Use a pain-free range and steady tempo. This is muscle work, not a grind.'},
        {n:'Cable Curl', sets:2, reps:'12', incLb:2.5, incKg:1, tip:'Let the biceps do the work. Avoid swinging or leaning back.'}
      ], finisher:'Optional 6–10 minutes of easy shadowboxing or bag work if you still feel fresh. Skip it if recovery is lagging.'},
      {day:6, title:'Rest / Light Movement', type:'rest', warmup:'No structured training required.', focus:'Walk, stretch, hydrate, and keep the body loose. Bank recovery.', recoveryTip:'Short walks, breathing drills, or easy mobility are enough.'},
      {day:7, title:'Rest / Light Movement', type:'rest', warmup:'Another full recovery day.', focus:'Sleep, hydrate, and prepare for the upcoming week.', recoveryTip:'A calm reset day improves consistency more than squeezing in extra work.'}
    ];

    const REPLACEMENTS = {
      'Deadlift':['Trap Bar Deadlift','Rack Pull','Cable Pull-Through'],
      'Bent-over Row':['Chest-Supported Row','Seated Cable Row','Machine Row'],
      'Lat Pulldown':['Assisted Pull-Up','Neutral-Grip Pulldown','Machine Pullover'],
      'Dumbbell Row':['Chest-Supported Row','Cable Row','Machine Row'],
      'Face Pulls':['Band Pull-Apart','Reverse Pec Deck','Cable Rear Delt Fly'],
      'Hammer Curls':['Cable Curl','EZ-Bar Curl','Incline Dumbbell Curl'],
      'Bench Press':['Machine Chest Press','Push-Up on Handles','Incline Dumbbell Bench Press'],
      'Dumbbell Shoulder Press':['Landmine Press','Machine Shoulder Press','Seated Arnold Press'],
      'Push-ups':['Incline Push-Up','Machine Chest Press','Smith Push-Up'],
      'Cable Lateral Raise':['Dumbbell Lateral Raise','Machine Lateral Raise','Single-Arm Cable Raise'],
      'Tricep Rope Extension':['Overhead Rope Extension','Cable Kickback','Machine Dip'],
      'Trap Bar Deadlift':['Goblet Squat to Box','Leg Press','Rack Pull'],
      'Leg Press':['Goblet Squat to Box','Split Squat with Support','Hack Squat (shallow ROM)'],
      'Dumbbell Lunges':['Step-Up','Split Squat with Support','Reverse Lunge'],
      'Hip Thrust':['Glute Bridge','Cable Pull-Through','Back Extension (glute focus)'],
      'Leg Curl':['Seated Leg Curl','Swiss Ball Curl','Sliding Leg Curl'],
      'Standing Calf Raise':['Seated Calf Raise','Leg Press Calf Raise','Bodyweight Calf Raise'],
      'Incline Dumbbell Bench Press':['Machine Incline Press','Flat Dumbbell Press','Push-Up on Handles'],
      'Chest-Supported Row':['Seated Cable Row','Machine Row','One-Arm Dumbbell Row'],
      'Romanian Deadlift':['Cable Pull-Through','Glute Bridge','Back Extension'],
      'Seated Dumbbell Shoulder Press':['Machine Shoulder Press','Landmine Press','High-Incline Press'],
      'Cable Curl':['Hammer Curl','EZ-Bar Curl','Machine Curl']
    };

    const ORIGINAL_ABS = [
      {n:'Plank', m:'4 × 30 sec'},
      {n:'Ab Crunch', m:'4 × 15'},
      {n:'Scissor Kicks', m:'4 × 12 each'},
      {n:'Bicycle', m:'4 × 15 each'},
      {n:'Lying Leg Raise', m:'4 × 12'},
      {n:'Sit Up', m:'4 × 15'}
    ];
    const ABS = [
      {n:'Front plank', m:'20–30 sec'}, {n:'Crunch', m:'10–15 reps'}, {n:'Bicycle', m:'10 each'}, {n:'Lying leg raise', m:'8–12 reps'}, {n:'Sit-up variation', m:'8–12 reps'}
    ];
    const REMINDERS = [
      {t:'Hydration', d:'Aim to start sessions already hydrated and keep water nearby. Clear to pale-yellow urine most of the day is a useful simple check.'},
      {t:'Sleep', d:'Prioritize 7–9 hours whenever possible. Poor sleep makes joint tolerance and recovery worse.'},
      {t:'Recovery pacing', d:'If joints feel worse after training, reduce load, cut a set, or trim Day 5 before forcing it.'},
      {t:'Effort control', d:'Most work should land around RPE 6–8. Smooth reps beat grinders.'}
    ];
    const PROGRESSION = [
      {w:'Weeks 1–2', d:'Learn the lifts again. Keep every set smooth and submaximal. Add no weight unless form is crisp and recovery is easy.'},
      {w:'Weeks 3–4', d:'Add 2.5–5 lb on upper-body lifts, 5–10 lb on lower-body lifts, or 1 rep to accessories if RPE stayed under about 7.5.'},
      {w:'Weeks 5–6', d:'Keep increases small. On Day 5 you can add a little load or one rep per set before adding more total work.'},
      {w:'Week 7', d:'Hold steady or slightly deload if fatigue, soreness, or sleep quality starts sliding.'},
      {w:'Week 8', d:'Consolidate. Match or slightly beat week 6 numbers with cleaner form and better recovery.'}
    ];
    const STORAGE_KEY = 'creed57.v3';
    const defaultState = {activeWeek:1, activeDay:1, unit:'lb', chartExercise:'Deadlift', coreMode:'scaled', done:{}, logs:{}, special:{}, swaps:{}, meals:[], bodyweights:[]};
    const state = Object.assign({}, defaultState, JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}'));
    state.meals = Array.isArray(state.meals) ? state.meals : [];
    state.bodyweights = Array.isArray(state.bodyweights) ? state.bodyweights : [];
    const $ = sel => document.querySelector(sel);
    const $$ = sel => Array.from(document.querySelectorAll(sel));
    const chartMoves = PROGRAM.filter(d => d.type==='lift').flatMap(d => d.exercises.map(ex => ex.n));
    const uniqueMoves = [...new Set(chartMoves)];
    const today = new Date().toISOString().slice(0,10);
    function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
    function dayData(day){ return PROGRAM.find(d => d.day === day); }
    function doneKey(w,d,e){ return `w${w}_d${d}_e${e}`; }
    function specialKey(w,d){ return `w${w}_d${d}`; }
    function logKey(w,d,e,s){ return `w${w}_d${d}_e${e}_s${s}`; }
    function swapKey(w,d,e){ return `w${w}_d${d}_e${e}`; }
    function getLog(w,d,e,s){ return state.logs[logKey(w,d,e,s)] || {weight:'', reps:'', rpe:''}; }
    function setLog(w,d,e,s,field,val){ const key=logKey(w,d,e,s); const current=state.logs[key] || {weight:'', reps:'', rpe:''}; current[field]=val; state.logs[key]=current; save(); renderChart(); renderExerciseList(); }
    function isDone(w,d,e){ return !!state.done[doneKey(w,d,e)]; }
    function toggleDone(w,d,e){ state.done[doneKey(w,d,e)] = !state.done[doneKey(w,d,e)]; save(); renderAll(); }
    function setSpecial(w,d,field,val){ const key=specialKey(w,d); const current=state.special[key] || {}; current[field]=val; state.special[key]=current; save(); renderExerciseList(); renderWeekPlanner(); renderProgress(); }
    function getSpecial(w,d){ return state.special[specialKey(w,d)] || {}; }
    function getSwap(w,d,e,original){ return state.swaps[swapKey(w,d,e)] || original; }
    function setSwap(w,d,e,value){ state.swaps[swapKey(w,d,e)] = value; save(); renderExerciseList(); }
    function clearDay(week, day){ const d=dayData(day); if(d.type==='lift'){ d.exercises.forEach((ex, exIndex)=>{ delete state.done[doneKey(week,day,exIndex)]; delete state.swaps[swapKey(week,day,exIndex)]; for(let s=1;s<=ex.sets;s++) delete state.logs[logKey(week,day,exIndex,s)]; }); } delete state.special[specialKey(week,day)]; save(); renderAll(); }
    function dayComplete(week, day){ const d=dayData(day); if(d.type==='lift') return d.exercises.every((_,i)=>isDone(week,day,i)); return !!getSpecial(week,day).done; }
    function weekPercent(week){ let done=0; for(let d=1;d<=7;d++) if(dayComplete(week,d)) done++; return Math.round(done / 7 * 100); }
    function exerciseRef(name){ for(const d of PROGRAM){ if(d.type!=='lift') continue; const exIndex=d.exercises.findIndex(ex=>ex.n===name); if(exIndex>-1) return {day:d.day, exIndex, ex:d.exercises[exIndex]}; } return null; }
    function historyFor(name){ const ref=exerciseRef(name); if(!ref) return []; return Array.from({length:8},(_,i)=>{ const week=i+1; let top=0,totalRpe=0,points=0; for(let s=1;s<=ref.ex.sets;s++){ const log=getLog(week,ref.day,ref.exIndex,s); const wt=Number(log.weight||0), rpe=Number(log.rpe||0); top=Math.max(top,wt); if(rpe){ totalRpe+=rpe; points++; } } return {week, top, avgRpe: points ? totalRpe/points : 0}; }); }
    function roundToStep(num, step){ return Math.round(num / step) * step; }
    function suggestion(ex){ const ref=exerciseRef(ex.n); if(!ref) return 'Build quality first. Add load only if reps stay smooth and joint-friendly.'; const hist=historyFor(ex.n); const current=hist.find(h=>h.week===state.activeWeek); const prior=hist.find(h=>h.week===Math.max(1, state.activeWeek-1)); const source=current && current.top ? current : prior; if(!source || !source.top) return 'Start conservative. If all sets feel like RPE 6–7 with clean form, a very small increase next week is enough.'; const step=state.unit==='lb' ? (ex.incLb || 2.5) : (ex.incKg || 1); let target=source.top; if(source.avgRpe && source.avgRpe <= 7.5) target += step; else if(source.avgRpe && source.avgRpe >= 9) target -= Math.max(step/2, state.unit==='lb' ? 2.5 : 1); target = roundToStep(target, state.unit==='lb' ? 2.5 : .5); return `If this lift stayed pain-free and around RPE ${source.avgRpe ? source.avgRpe.toFixed(1) : '7–8'}, next week try about ${target} ${state.unit}.`; }
    function demoUrl(name){ return `https://www.youtube.com/results?search_query=${encodeURIComponent(name + ' proper form for beginners')}`; }
    function beep(){ const ctx=new (window.AudioContext||window.webkitAudioContext)(); const osc=ctx.createOscillator(), gain=ctx.createGain(); osc.type='sine'; osc.frequency.value=880; gain.gain.value=0.12; osc.connect(gain); gain.connect(ctx.destination); osc.start(); setTimeout(()=> osc.frequency.value=660, 170); setTimeout(()=>{ osc.stop(); ctx.close(); }, 420); }
    function fmtNum(v){ return Number(v).toFixed(state.unit==='lb' ? 1 : 1).replace(/\.0$/,''); }
    function getCoreRoutine(){ return state.coreMode === 'original' ? ORIGINAL_ABS : ABS; }

    function renderWeekPlanner(){ const grid=$('#weekGrid'); grid.innerHTML=''; for(let week=1;week<=8;week++){ const card=document.createElement('div'); card.className=`week-card ${week===state.activeWeek?'active':''}`; card.innerHTML=`<div class="week-head"><strong>Week ${week}</strong><span class="week-pct">${weekPercent(week)}%</span></div><div class="day-mini"></div>`; const miniWrap=card.querySelector('.day-mini'); for(let day=1;day<=7;day++){ const mini=document.createElement('button'); mini.className=`mini ${dayComplete(week,day)?'done':''} ${(week===state.activeWeek&&day===state.activeDay)?'active':''}`; mini.textContent=day; mini.addEventListener('click',e=>{ e.stopPropagation(); state.activeWeek=week; state.activeDay=day; $('#weekSelect').value=week; save(); renderAll(); }); miniWrap.appendChild(mini);} card.addEventListener('click',()=>{ state.activeWeek=week; $('#weekSelect').value=week; save(); renderAll();}); grid.appendChild(card);} }
    function renderProgression(){ const list=$('#progressionList'); list.innerHTML=''; PROGRESSION.forEach(item=>{ const div=document.createElement('div'); div.className='prog-item'; div.innerHTML=`<b>${item.w}</b><span>${item.d}</span>`; list.appendChild(div); }); }
    function renderReminders(){ const list=$('#reminderList'); list.innerHTML=''; REMINDERS.forEach(item=>{ const div=document.createElement('div'); div.className='reminder'; div.innerHTML=`<b>${item.t}</b><span>${item.d}</span>`; list.appendChild(div); }); }
    function renderTabs(){ const tabs=$('#tabs'); tabs.innerHTML=''; PROGRAM.forEach(day=>{ const btn=document.createElement('button'); btn.className=`tab ${state.activeDay===day.day?'active':''}`; const short=day.day===1?'Pull':day.day===2?'Push':day.day===3?'Recover':day.day===4?'Legs':day.day===5?'Muscle': 'Rest'; btn.innerHTML=`<small>Day ${day.day}</small><strong>${short}</strong>`; btn.addEventListener('click',()=>{ state.activeDay=day.day; save(); renderAll();}); tabs.appendChild(btn);}); }
    function replacementSelect(original, exIndex){ const alts=[original].concat(REPLACEMENTS[original] || []); const selected=getSwap(state.activeWeek, state.activeDay, exIndex, original); return `<select class="field swapSelect" data-ex="${exIndex}">${alts.map(opt=>`<option ${opt===selected?'selected':''}>${opt}</option>`).join('')}</select>`; }
    function renderLiftDay(d, list){ d.exercises.forEach((ex, exIndex)=>{ const done=isDone(state.activeWeek,state.activeDay,exIndex); const currentName=getSwap(state.activeWeek,state.activeDay,exIndex,ex.n); const card=document.createElement('article'); card.className=`ex ${done?'done':''}`; card.innerHTML=`<div class="ex-head"><div class="num">${String(exIndex+1).padStart(2,'0')}</div><div><div class="name">${currentName}<small>${ex.tip}</small></div><div class="ex-actions"><a class="button slim alt" href="${demoUrl(currentName)}" target="_blank" rel="noopener">Form video</a><button class="button slim ${done?'alt':'primary'} doneBtn">${done?'Completed':'Mark complete'}</button></div></div><div class="sr"><b>${ex.sets} sets</b><span>${ex.reps} reps</span></div></div><div class="form-row" style="margin-top:12px"><label class="pill" style="flex:1 1 260px">Exercise swap ${replacementSelect(ex.n, exIndex)}</label></div><div class="hint">${suggestion(ex)}</div><div class="form-tip">Age-appropriate intensity: stop the set when technique slows down or joint discomfort builds. Smooth reps beat heroic reps.</div><div class="set-table"><div class="set-head"><div>Set</div><div>Weight (${state.unit})</div><div>Reps</div><div>RPE</div></div></div>`;
        card.querySelector('.doneBtn').addEventListener('click',()=>toggleDone(state.activeWeek,state.activeDay,exIndex));
        card.querySelector('.swapSelect').addEventListener('change',e=>setSwap(state.activeWeek,state.activeDay,exIndex,e.target.value));
        const table=card.querySelector('.set-table');
        for(let s=1;s<=ex.sets;s++){
          const log=getLog(state.activeWeek,state.activeDay,exIndex,s); const row=document.createElement('div'); row.className='set-row'; row.innerHTML=`<div class="cell">${s}</div><input class="field" inputmode="decimal" type="number" step="${state.unit==='lb'?'2.5':'0.5'}" value="${log.weight}" placeholder="${ex.bodyweight?'added load':'weight'}" /><input class="field" inputmode="numeric" type="number" step="1" value="${log.reps}" placeholder="${ex.reps}" /><input class="field" inputmode="decimal" type="number" min="1" max="10" step="0.5" value="${log.rpe}" placeholder="7.0" />`;
          const [weight,reps,rpe]=row.querySelectorAll('input'); weight.addEventListener('input',e=>setLog(state.activeWeek,state.activeDay,exIndex,s,'weight',e.target.value)); reps.addEventListener('input',e=>setLog(state.activeWeek,state.activeDay,exIndex,s,'reps',e.target.value)); rpe.addEventListener('input',e=>setLog(state.activeWeek,state.activeDay,exIndex,s,'rpe',e.target.value)); table.appendChild(row);
        }
        list.appendChild(card);
      }); const finisher=document.createElement('div'); finisher.className='special-card'; finisher.innerHTML=`<h3>Conditioning note</h3><div class="muted">${d.finisher}</div>`; list.appendChild(finisher);
    }
    function renderRecoveryLikeDay(d, list){ const log=getSpecial(state.activeWeek,state.activeDay); const options=(d.options||[]).map(opt=>`<label class="option"><input type="radio" name="specialChoice" value="${opt.n}" ${log.choice===opt.n?'checked':''} style="margin-right:8px"><b>${opt.n}</b><span>${opt.d}</span></label>`).join(''); const activeCore=getCoreRoutine(); const card=document.createElement('div'); card.className='special-card'; card.innerHTML=`<h3>${d.title}</h3><div class="muted">${d.recoveryTip}</div><div class="list-block" style="margin-top:14px">${options}</div><div class="form-row" style="margin-top:14px"><input class="field" id="specialMinutes" type="number" step="1" min="0" value="${log.minutes||''}" placeholder="Minutes" /><input class="field" id="specialNotes" type="text" value="${log.notes||''}" placeholder="How it felt" /><button class="button ${log.done?'alt':'primary'}" id="specialDone">${log.done?'Completed':'Mark complete'}</button></div>${d.day===3 ? `<div class="form-tip">Suggested ab circuit (${state.coreMode === 'original' ? 'original full routine' : '57+ scaled routine'}): ${activeCore.map(a=>`${a.n} ${a.m}`).join(' · ')}.</div>` : ''}`; list.appendChild(card); card.querySelectorAll('input[name="specialChoice"]').forEach(el=>el.addEventListener('change',e=>setSpecial(state.activeWeek,state.activeDay,'choice',e.target.value))); card.querySelector('#specialMinutes').addEventListener('input',e=>setSpecial(state.activeWeek,state.activeDay,'minutes',e.target.value)); card.querySelector('#specialNotes').addEventListener('input',e=>setSpecial(state.activeWeek,state.activeDay,'notes',e.target.value)); card.querySelector('#specialDone').addEventListener('click',()=>setSpecial(state.activeWeek,state.activeDay,'done',!getSpecial(state.activeWeek,state.activeDay).done)); }
    function renderRestDay(d, list){ const log=getSpecial(state.activeWeek,state.activeDay); const card=document.createElement('div'); card.className='special-card'; card.innerHTML=`<h3>${d.title}</h3><div class="muted">${d.recoveryTip}</div><div class="form-row" style="margin-top:14px"><input class="field" id="restActivity" type="text" value="${log.notes||''}" placeholder="Walk, mobility, breathing" /><input class="field" id="restMinutes" type="number" step="1" min="0" value="${log.minutes||''}" placeholder="Minutes" /><button class="button ${log.done?'alt':'primary'}" id="restDoneBtn">${log.done?'Recovered':'Mark recovery complete'}</button></div><div class="form-tip">These days matter. Better sleep, hydration, and lower joint irritation are part of the program.</div>`; list.appendChild(card); card.querySelector('#restActivity').addEventListener('input',e=>setSpecial(state.activeWeek,state.activeDay,'notes',e.target.value)); card.querySelector('#restMinutes').addEventListener('input',e=>setSpecial(state.activeWeek,state.activeDay,'minutes',e.target.value)); card.querySelector('#restDoneBtn').addEventListener('click',()=>setSpecial(state.activeWeek,state.activeDay,'done',!getSpecial(state.activeWeek,state.activeDay).done)); }
    function renderExerciseList(){ const d=dayData(state.activeDay); $('#dayHeadline').textContent=`Week ${state.activeWeek} · Day ${state.activeDay}`; $('#panelTitle').textContent=d.title; $('#panelMeta').textContent=d.type==='lift' ? `${d.exercises.length} exercises · joint-conscious loading · boxing theme intact` : d.type==='recovery' ? 'Restorative day · low stress only' : 'Recovery-focused rest day'; $('#warmup').innerHTML=`<span class="badge">Warm-up</span><div>${d.warmup}</div>`; $('#focusNote').textContent=d.focus; const list=$('#exerciseList'); list.innerHTML=''; if(d.type==='lift') renderLiftDay(d,list); else if(d.type==='recovery') renderRecoveryLikeDay(d,list); else renderRestDay(d,list); renderProgress(); }
    function renderProgress(){ const d=dayData(state.activeDay); const total=d.type==='lift' ? d.exercises.length : 1; const done=d.type==='lift' ? d.exercises.filter((_,i)=>isDone(state.activeWeek,state.activeDay,i)).length : (dayComplete(state.activeWeek,state.activeDay)?1:0); const pct=Math.round(done/total*100); $('#progressBar').style.width=`${pct}%`; $('#progressPct').textContent=`${pct}%`; }
    function renderChart(){ const history=historyFor(state.chartExercise); const current=history.find(h=>h.week===state.activeWeek)||{top:0}; const best=history.reduce((acc,cur)=>cur.top>acc.top?cur:acc,{week:'—',top:0}); $('#metricCurrent').textContent=current.top?`${current.top} ${state.unit}`:'—'; $('#metricBest').textContent=best.top?`W${best.week} · ${best.top} ${state.unit}`:'—'; const first=history.find(h=>h.top>0), last=[...history].reverse().find(h=>h.top>0); $('#metricTrend').textContent=first&&last&&first.week!==last.week?`${last.top-first.top>0?'+':''}${last.top-first.top} ${state.unit}`:'No trend yet'; drawLineChart($('#chart'), history.map(h=>({label:`W${h.week}`, value:h.top})), 'Log some working weights to draw your line.'); }
    function drawLineChart(canvas, points, emptyMsg){ const ctx=canvas.getContext('2d'); const w=canvas.width, h=canvas.height; ctx.clearRect(0,0,w,h); ctx.fillStyle='#0f0f14'; ctx.fillRect(0,0,w,h); const pad={l:46,r:18,t:16,b:30}; const plotW=w-pad.l-pad.r, plotH=h-pad.t-pad.b; const max=Math.max(...points.map(p=>Number(p.value)||0),0); const topMax=max?max*1.15:100; ctx.strokeStyle='#2a2a35'; ctx.lineWidth=1; for(let i=0;i<5;i++){ const y=pad.t+(plotH/4)*i; ctx.beginPath(); ctx.moveTo(pad.l,y); ctx.lineTo(w-pad.r,y); ctx.stroke(); } ctx.fillStyle='#8f8f9b'; ctx.font='12px system-ui'; for(let i=0;i<5;i++){ const value=Math.round(topMax-(topMax/4)*i); ctx.fillText(String(value),8,pad.t+(plotH/4)*i+4); } points.forEach((p,i)=>{ const x=pad.l+(plotW/Math.max(points.length-1,1))*i; ctx.fillText(p.label,x-12,h-10); }); if(!points.some(p=>Number(p.value)>0)){ ctx.fillStyle='#b4b4bf'; ctx.font='16px system-ui'; ctx.fillText(emptyMsg, 140, 140); return; } ctx.beginPath(); points.forEach((p,i)=>{ const x=pad.l+(plotW/Math.max(points.length-1,1))*i; const y=pad.t+plotH-((Number(p.value)||0)/topMax)*plotH; if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y); }); ctx.strokeStyle='#ffd23f'; ctx.lineWidth=3; ctx.stroke(); points.forEach((p,i)=>{ const x=pad.l+(plotW/Math.max(points.length-1,1))*i; const y=pad.t+plotH-((Number(p.value)||0)/topMax)*plotH; ctx.beginPath(); ctx.arc(x,y, Number(p.value)?5:3, 0, Math.PI*2); ctx.fillStyle=Number(p.value)?'#e11d2e':'#4b4b56'; ctx.fill(); if(Number(p.value)){ ctx.fillStyle='#f4f4f7'; ctx.fillText(String(p.value), x-10, y-10); } }); }
    function renderBodyweight(){ $('#bwDate').value = $('#bwDate').value || today; const sorted=[...state.bodyweights].sort((a,b)=>a.date.localeCompare(b.date)); $('#bwCount').textContent=sorted.length; const latest=sorted[sorted.length-1]; const first=sorted[0]; $('#bwLatest').textContent=latest ? `${latest.weight} ${state.unit}` : '—'; $('#bwChange').textContent=(latest&&first&&sorted.length>1) ? `${(latest.weight-first.weight>0?'+':'')}${(latest.weight-first.weight).toFixed(1)} ${state.unit}` : '—'; drawLineChart($('#bwChart'), sorted.map(r=>({label:r.date.slice(5), value:r.weight})), 'Add bodyweight check-ins to see your trend.'); const list=$('#bwList'); list.innerHTML=''; sorted.slice().reverse().slice(0,6).forEach((row, idx)=>{ const div=document.createElement('div'); div.className='list-item'; div.innerHTML=`<b>${row.date} · ${row.weight} ${state.unit}</b><span>${row.note || 'No note'}</span>`; list.appendChild(div); }); }
    function addBodyweight(){ const date=$('#bwDate').value || today; const weight=Number($('#bwWeight').value); const note=$('#bwNote').value.trim(); if(!weight) return; state.bodyweights.push({date, weight, note}); state.bodyweights.sort((a,b)=>a.date.localeCompare(b.date)); $('#bwWeight').value=''; $('#bwNote').value=''; save(); renderBodyweight(); }
    function mealEntriesFor(date){ return state.meals.filter(m=>m.date===date); }
    function renderMeals(){ $('#mealDate').value = $('#mealDate').value || today; const date=$('#mealDate').value; $('#mealDateBadge').textContent=date || '—'; const meals=mealEntriesFor(date); const totals=meals.reduce((acc,m)=>({protein:acc.protein+Number(m.protein||0), carbs:acc.carbs+Number(m.carbs||0), fat:acc.fat+Number(m.fat||0), calories:acc.calories+Number(m.calories||0)}), {protein:0, carbs:0, fat:0, calories:0}); $('#sumProtein').textContent=`${totals.protein} g`; $('#sumCarbs').textContent=`${totals.carbs} g`; $('#sumFat').textContent=`${totals.fat} g`; $('#sumCalories').textContent=String(totals.calories); $('#sumMeals').textContent=String(meals.length); const list=$('#mealList'); list.innerHTML=''; if(!meals.length){ list.innerHTML='<div class="list-item"><b>No meals logged</b><span>Add a meal for the selected date to start tracking your macros.</span></div>'; return; } meals.forEach((meal,index)=>{ const row=document.createElement('div'); row.className='macro-row'; row.innerHTML=`<div class="list-item"><b>${meal.type}: ${meal.name || 'Meal'}</b><span>${meal.notes || 'No notes'}</span></div><div class="chip">P ${meal.protein||0}</div><div class="chip">C ${meal.carbs||0}</div><div class="chip">F ${meal.fat||0}</div><div class="chip">Cal ${meal.calories||0}</div><button class="delete-btn" data-id="${meal.id}">Delete</button>`; list.appendChild(row); }); list.querySelectorAll('.delete-btn').forEach(btn=>btn.addEventListener('click',()=>{ state.meals=state.meals.filter(m=>m.id!==btn.dataset.id); save(); renderMeals(); })); }
    function addMeal(){ const date=$('#mealDate').value || today; const type=$('#mealType').value; const name=$('#mealName').value.trim(); const protein=Number($('#mealProtein').value||0); const carbs=Number($('#mealCarbs').value||0); const fat=Number($('#mealFat').value||0); const calories=Number($('#mealCalories').value||0); const notes=$('#mealNotes').value.trim(); if(!name && !protein && !carbs && !fat && !calories) return; state.meals.push({id:`meal_${Date.now()}`, date, type, name, protein, carbs, fat, calories, notes}); ['mealName','mealProtein','mealCarbs','mealFat','mealCalories','mealNotes'].forEach(id=>$('#'+id).value=''); save(); renderMeals(); }
    function exportHistory(){ const payload={exported_at:new Date().toISOString(), app:'Creed 57+ Fighter Reset', data:state}; const blob=new Blob([JSON.stringify(payload,null,2)], {type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`creed57-history-${new Date().toISOString().slice(0,10)}.json`; document.body.appendChild(a); a.click(); setTimeout(()=>{ URL.revokeObjectURL(a.href); a.remove(); }, 0); }
    function importHistory(file){ const reader=new FileReader(); reader.onload=()=>{ try{ const parsed=JSON.parse(reader.result); const data=parsed.data || parsed; const next=Object.assign({}, defaultState, data); localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); Object.keys(state).forEach(k=>delete state[k]); Object.assign(state, next); renderAll(); alert('History imported successfully.'); } catch(err){ alert('Import failed. Please choose a valid export file.'); } }; reader.readAsText(file); }
    function renderSelectors(){ $('#weekSelect').value=String(state.activeWeek); $('#unitSelect').value=state.unit; const sel=$('#chartExercise'); if(!sel.options.length) uniqueMoves.forEach(move=>{ const opt=document.createElement('option'); opt.value=move; opt.textContent=move; sel.appendChild(opt); }); if(!uniqueMoves.includes(state.chartExercise)) state.chartExercise=uniqueMoves[0]; sel.value=state.chartExercise; }
    function renderCore(){ const headline=$('#coreHeadline'); const list=$('#coreList'); if(!headline || !list) return; const usingOriginal = state.coreMode === 'original'; const routine = getCoreRoutine(); headline.textContent = usingOriginal ? 'Original Creed core: the full 6-move ab routine from the first app.' : '57+ scaled core: lower-volume version built for recovery and consistency.'; list.innerHTML=''; routine.forEach(item=>{ const div=document.createElement('div'); div.className='list-item'; div.innerHTML=`<b>${item.n}</b><span>${item.m}</span>`; list.appendChild(div); }); const originalBtn=$('#coreOriginalBtn'); const scaledBtn=$('#coreScaledBtn'); if(originalBtn && scaledBtn){ originalBtn.className = `button slim ${usingOriginal ? 'primary' : 'alt'}`; scaledBtn.className = `button slim ${usingOriginal ? 'alt' : 'primary'}`; }
    }
    function renderAll(){ renderSelectors(); renderWeekPlanner(); renderProgression(); renderReminders(); renderTabs(); renderExerciseList(); renderChart(); renderBodyweight(); renderMeals(); renderCore(); }

    $('#weekSelect').addEventListener('change',e=>{ state.activeWeek=Number(e.target.value); save(); renderAll(); });
    $('#unitSelect').addEventListener('change',e=>{ state.unit=e.target.value; save(); renderAll(); });
    $('#chartExercise').addEventListener('change',e=>{ state.chartExercise=e.target.value; save(); renderChart(); });
    $('#resetDay').addEventListener('click',()=>clearDay(state.activeWeek,state.activeDay));
    $('#addBwBtn').addEventListener('click',addBodyweight);
    $('#bwDate').value=today; $('#mealDate').value=today;
    $('#mealDate').addEventListener('change',renderMeals);
    $('#addMealBtn').addEventListener('click',addMeal);
    $('#exportBtn').addEventListener('click',exportHistory);
    $('#importBtn').addEventListener('click',()=>$('#importFile').click());
    $('#importFile').addEventListener('change',e=>{ const file=e.target.files[0]; if(file) importHistory(file); e.target.value=''; });
    $('#coreOriginalBtn').addEventListener('click',()=>{ state.coreMode='original'; save(); renderCore(); renderExerciseList(); });
    $('#coreScaledBtn').addEventListener('click',()=>{ state.coreMode='scaled'; save(); renderCore(); renderExerciseList(); });

    let promptEvent=null; window.addEventListener('beforeinstallprompt',e=>{ e.preventDefault(); promptEvent=e; $('#installBtn').style.display='inline-flex'; }); $('#installBtn').addEventListener('click',async()=>{ if(!promptEvent) return; promptEvent.prompt(); await promptEvent.userChoice; promptEvent=null; $('#installBtn').style.display='none'; }); if('serviceWorker' in navigator){ window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{})); }
    let timerSecs=90, timerLeft=90, timerId=null; function drawTimer(){ $('#timerDisplay').textContent=`${String(Math.floor(timerLeft/60)).padStart(2,'0')}:${String(timerLeft%60).padStart(2,'0')}`; }
    $('#timerFab').addEventListener('click',()=>$('#timerModal').classList.add('open')); $('#timerClose').addEventListener('click',()=>$('#timerModal').classList.remove('open')); $('#timerReset').addEventListener('click',()=>{ clearInterval(timerId); timerId=null; timerLeft=timerSecs; $('#timerStart').textContent='Start'; drawTimer(); }); $('#timerStart').addEventListener('click',()=>{ if(timerId){ clearInterval(timerId); timerId=null; $('#timerStart').textContent='Start'; return; } $('#timerStart').textContent='Pause'; timerId=setInterval(()=>{ timerLeft--; drawTimer(); if(timerLeft<=0){ clearInterval(timerId); timerId=null; $('#timerStart').textContent='Start'; timerLeft=timerSecs; beep(); drawTimer(); } },1000); }); $$('.preset-row .button').forEach(btn=>btn.addEventListener('click',()=>{ timerSecs=Number(btn.dataset.sec); timerLeft=timerSecs; drawTimer(); }));
    drawTimer(); renderAll();
